from typing import List, Dict

VERB_TO_TOOL_MAPPING: Dict[str, List[str]] = {
    "read": ["read_file", "get_function_definition"],
    "reading": ["read_file", "get_function_definition"],
    "write": ["write_file", "edit_file"],
    "writing": ["write_file", "edit_file"],
    "search": ["search_code"],
    "searching": ["search_code"],
    "find": ["search_code", "list_directory"],
    "finding": ["search_code", "list_directory"],
    "edit": ["edit_file", "write_file"],
    "editing": ["edit_file", "write_file"],
    "fix": ["edit_file"],
    "fixing": ["edit_file"],
    "run": ["run_terminal_command"],
    "running": ["run_terminal_command"],
    "execute": ["run_terminal_command"],
    "executing": ["run_terminal_command"],
    "list": ["list_directory"],
    "listing": ["list_directory"],
    "check": ["read_file", "search_code"],
    "checking": ["read_file", "search_code"],
    "examine": ["read_file", "get_function_definition"],
    "examining": ["read_file", "get_function_definition"],
    "look": ["read_file", "search_code"],
    "looking": ["read_file", "search_code"],
    "view": ["read_file"],
    "viewing": ["read_file"],
    "create": ["write_file"],
    "creating": ["write_file"],
    "modify": ["edit_file"],
    "modifying": ["edit_file"],
    "change": ["edit_file"],
    "changing": ["edit_file"],
    "update": ["edit_file"],
    "updating": ["edit_file"],
}

ACTION_PATTERNS: List[str] = [
    r"I'll\s+(\w+)\s+(?:the\s+)?(.+?)(?:\.|,|$)",
    r"I\s+will\s+(\w+)\s+(?:the\s+)?(.+?)(?:\.|,|$)",
    r"Let me\s+(\w+)\s+(?:the\s+)?(.+?)(?:\.|,|$)",
    r"I'm going to\s+(\w+)\s+(?:the\s+)?(.+?)(?:\.|,|$)",
    r"I am going to\s+(\w+)\s+(?:the\s+)?(.+?)(?:\.|,|$)",
    r"First,?\s+I'll\s+(\w+)\s+(?:the\s+)?(.+?)(?:\.|,|$)",
    r"First,?\s+I\s+will\s+(\w+)\s+(?:the\s+)?(.+?)(?:\.|,|$)",
    r"Next,?\s+I'll\s+(\w+)\s+(?:the\s+)?(.+?)(?:\.|,|$)",
    r"Then,?\s+I'll\s+(\w+)\s+(?:the\s+)?(.+?)(?:\.|,|$)",
    r"(\w+)ing\s+(?:the\s+)?(.+?)(?:\.|,|$)",
]

